### ISSUE TITLE
HA Zone not working

### ISSUE THREAD

**Issue by ElVit** [mrgadget/node-red-contrib-eztimer#51]
Hi,

first of all thanks for this nice node.
I'm using NodeRed as a Home Assistant Addon.
When I set "Geo Source" = "HomeAssistant Zone" then the "HA Zone" DropDownMenu shows no entries.

Can you tell me why? 
Did I miss some thing in my Home Assistant configuration?
I have already configured two additional Zones (in addition to the default "Home" Zone) over the "Map" Tab in HomeAssistant.

![grafik](https://user-images.githubusercontent.com/54866762/137482143-2f169cac-93b7-4ff0-a724-a628fd1793b8.png)

**Comment by mrgadget** [comment]
Yep this is the same way I use it - do you have the Home Assistant websocket node installed within node-red (settings > manage palette)?  That's the node that provides the functionality to hook back into Home Assistant.

![image](https://user-images.githubusercontent.com/700522/137567954-9ed46174-c4e4-4bb3-9542-65636978f499.png)

**Comment by ElVit** [comment]
Yes I the websocket node is installed. 
I didn’t delete any nodes from the palette. Only adding some. The websocket node is preinstalled right, when using the Home Assistant addon? Do I have to configure something special in the addon options?

**Comment by mrgadget** [comment]
Without being able to replicate at my end, we're going to need to troubleshoot to figure out why it's not working for you.

So I have installed;
* Node-RED
* **node-red-contrib-home-assistant-websocket** installed within Node-RED (unsure if this is automatically installed or not, it's been a while!)
* **Node-RED Companion** integration installed using **HACS**

Are you familiar with the debug tools in Chrome or Edge-Chomium?

What I'm wanting to know is what response you're getting when your browser makes the XHR request for `eztimer/getHaZones`.  Eztimer registers this endpoint when the node is loaded, and then calls the endpoint from the browser to load the zones from HA.

We want to see something like this returned:
```json
[
  {"entity_id":"zone.home","name":"Home","latitude":-34.567,"longitude":123.456}, 
  {"entity_id":"zone.test","name":"Test Zone","latitude":-45.678,"longitude":120.123}
]
```

**Comment by sihartley** [comment]
I have the exact same issue as this one here.
If I set Geo Source to HomeAssistant Zone, the HA Zone dropdown doesn't populate...

These are also installed...
      - Node-RED
      - node-red-contrib-home-assistant-websocket v0.38.0 installed within Node-RED 
      - Node-RED Companion integration installed using HACS

But the HA Zone dropdown does not populate...

**Comment by mrgadget** [comment]
Hi Simon - this still eludes me.  I can't fault it on my systems.  Obviously there's something I'm missing here!

Are you able to try my suggestion in my previous post please?

**Comment by mrgadget** [comment]
Just re-read code again.  Still interested in the result of the above - but something else you can check is do you have the `homeassistant` object in the global context in NodeRED? 

The call I make in the backend to get the zones is:
```js
let ha = node.context().global.get('homeassistant');
```

If that object doesn't exist, the call will fail.

You can access the global context from the right-hand pane in NodeRED:

![image](https://user-images.githubusercontent.com/700522/142741335-2a134f41-6b20-4705-9584-bff1e1da754c.png)

You'll need to hit the refresh button to show the contents of the global context:

![image](https://user-images.githubusercontent.com/700522/142741352-c2e2c7fc-c1a1-4f4f-921b-5bef7761723b.png)

**Comment by sihartley** [comment]
Hey Ben, thanks for getting back to me.
Honestly, I had just given up, and moved in a different direction. However, I have just tried the node again, and... Somehow it has simply started working as you designed it to!
The list now populates, and all of my zones are there. The thing is I have no idea what triggered it to start working, I think there have been a couple of HA updates since, as well as others.
So I am sorry I am unable to shed any light on the cause or solution to the issue.  But I can't express how much I appreciate you getting back to me, and trying to help.

**Comment by sihartley** [comment]
I did just check if the homeassistant object is in the global context in Node-Red, and it is... Not sure if it was there before it started working because this is now there, or not...

**Comment by mrgadget** [comment]
Thanks Simon!  Yes hard to fix something that you can't break isn't it?

It may well've been the lack of that object.  Perhaps a restart of NodeRED after the installation? Was eztimer a fresh install when you had the issue?

Hopefully @ElVit comes back with some info if it's still broken for them.

**Comment by sihartley** [comment]
No it wasn't a fresh install, and it wasn't due to a Node Red restart.
I installed the node, and later, a lot later after multiple restarts, updates etc. Eventually went to use the node the problem was there. 
I found the issue with the node, went in a different direction. Then when I went to try it again the problem had just worked itself out....

This maybe the case  with @ElVit, and they didn't get back here... ?
I can understand how frustrating this probably is for you, because there is maybe a bug you want to fix, and can't do that without diagnostic troubleshooting.
I feel the same frustration because I engaged you for an issue that is no longer apparent!  🤐

**Comment by mrgadget** [comment]
Ok - thanks Simon.  You may well be right.  I'm going to close this for now - happy to re-open if we can re-produce.

**Comment by sihartley** [comment]
Hey Ben,
I think I may have some insight into this issue. I added the eztimer node to a new flow today, and again the HA Zone list wasn't populated. However, I deployed the flow, then after that flow deployment I went into the eztimer node settings and the list was populated.
So basically, the node has to be deployed once before the HA Zone list will populate.
I don't know if this is a fault or if it is how, you designed the node to work. I do see where this would confuse people, usually when you add a node, the settings are adjusted before deployment...?

**Comment by mrgadget** [comment]
Ah now you might be on to something.  It works fine before it's deployed for me - _but_ I've got it multiple other places.  So I wonder now if you just need _one_ node deployed for the http listener to start.

Are you able to try that for me please? Have one eztimer deployed (doesn't need to be a HA zone one), then just drop another one from the palette and see if the HA zones work prior to deployment for the second (and subsequent) nodes.

I've got my fingers crossed!

**Comment by sihartley** [comment]
That's it!!!
If you have an instance of the node already deployed, the others will have the HA Zone lists populated whether they have been deployed or not, straight out of the box!!

**Comment by ElVit** [comment]
Hi all,
sorry for my late reply. I had not much time in the past for working on my home assistant stuff.
Thanks for the hint to use **full** deployment in node red.
Its also working for me now 😃

**Comment by mrgadget** [comment]
Thanks @ElVit - no worries, open source stuff doesn't always get priority in my life either - hence I can take a while to respond to stuff too!

Think we might've nailed it here, but unfortunately I don't see a way forward programmatically.  I'll put a conditional tip in the next build so if the HA zone list is empty it gives you an indicator that you might need to deploy to get it to populate.

Thanks for your help @ElVit @sihartley  

I'll leave this open until I publish the change so people can find this.

**Comment by LaurenceKaye** [comment]
I've just tried to use the latest version of this today and my zone list is also not populating. It doesn't seem to be due to the need to deploy first, the call to eztimer/getHaZones returns a 404 error instead.

Am I going wrong somewhere?


Home Assistant Core: 2021.12.9
Home Assistant Supervisor: 2021.12.2
Node-Red Add-on version: 10.3.2
Node-Red version: 2.1.5
eztimer version: 1.2.7

**Comment by dgthomson** [comment]
I've noticed this today.

HA 2022.11.5 in Docker
NR 3.0.2 in Docker
node-red-contrib-home-assistant-websocket 0.47.1
node-red-contrib-eztimer 1.2.7

In the node-red logs, there's this, which is right in the code that gets the zones from HA...

`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /data/node_modules/node-red-contrib-eztimer/index.js:63:34
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:144:13)
    at /usr/src/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:75:13
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:15`

**Comment by dgthomson** [comment]
> I've noticed this today.

Quickest error report and fix ever, I've sussed out the problem.

In the configuration node for node-red-contrib-home-assistant-websocket, there's a checkbox marked  'Enable global context store'. Make sure this is checked! Eztimer can then find the zones.

If this is still being developed, maybe the code should check if it has access to the home assistant global context store and stick a message up if it doesn't to give a bit of a clue.

**Comment by sdetweil** [comment]
AND I'm running NR in a docker container, beside HA in a docker container..  and didn't config anything in NR to find HA...
